configurationOverrides: {}
cp-schema-registry:
  url: ""
external:
  enabled: false
  externalTrafficPolicy: Cluster
  port: 8088
  type: LoadBalancer
image: confluentinc/cp-ksql-server
imagePullPolicy: IfNotPresent
imagePullSecrets: null
imageTag: 5.0.1
jmx:
  port: 5555
kafka:
  bootstrapServers: ""
ksql:
  headless: true
nodeSelector: {}
podAnnotations: {}
prometheus:
  jmx:
    enabled: true
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    port: 5556
replicaCount: 1
resources: {}
servicePort: 8088
tolerations: {}
