brokers: 3
configurationOverrides:
  advertised.listeners: EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
  listener.security.protocol.map: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
  offsets.topic.replication.factor: "3"
cp-zookeeper:
  enabled: true
  persistence:
    dataDirSize: 5Gi
    dataLogDirSize: 5Gi
    enabled: true
  servers: 3
  url: ""
customEnv: {}
heapOptions: -Xms1G -Xmx1G
image: confluentinc/cp-kafka
imagePullPolicy: IfNotPresent
imagePullSecrets: null
imageTag: 5.0.1
jmx:
  port: 5555
nodeSelector: {}
nodeport:
  enabled: false
  firstListenerPort: 31090
  servicePort: 19092
persistence:
  disksPerBroker: 1
  enabled: true
  size: 1Gi
podAnnotations: {}
podManagementPolicy: OrderedReady
prometheus:
  jmx:
    enabled: true
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    port: 5556
resources: {}
tolerations: {}
updateStrategy: RollingUpdate
