apiVersion: v1
dependencies:
- name: cp-helm-charts
  repository: https://confluentinc.github.io/cp-helm-charts/
  version: 0.1.0
description: Egeria lab environment
home: https://github.com/odpi/egeria
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
- odpi, egeria, lab, jupyter, notebook
maintainers:
- email: chris@thegrotes.net
  name: Christopher Grote
- email: nigel.l.jones+git@gmail.com
  name: Nigel Jones
name: lab
sources:
- https://github.com/odpi/egeria
version: 0.1.0
