# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
name: EgeriaPalisadeDemo
description: Egeria and Palisade demo/lab environment
version: 0.1.0
icon: https://raw.githubusercontent.com/odpi/egeria/99016e77167fa30dcfade809b061358a92a59973/assets/img/egeria.png
keywords:
  - ranger, security, odpi, egeria, open-metadata, palisade, lab, demo
sources:
  - https://github.com/odpi/egeria
  - https://github.com/odpi/palisade
  - https://github.com/odpi/egeria-palisade
home: https://github.com/odpi/egeria-palisade
maintainers:
  - name: Nigel Jones
    email: nigel.l.jones+git@gmail.com
