apiVersion: v1
kind: PersistentVolume
metadata:
    name: palisade-pv-volume
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "{{ .Values.configureexample.hostpath }}"